name: '${name}'
main: '${group}.v2.CrazyAuctionsPlus'

authors: [badbones69, ryderbelserion]

version: '${version}'
api-version: '${minecraft}'
description: '${description}'
website: '${website}'
folia-supported: true

depend: [Vault]

permissions:
  crazyauctions.cancel:
    default: true

  crazyauctions.access:
    default: true

  crazyauctions.bid:
    default: true

  crazyauctions.sell:
    default: true

  crazyauctions.expired:
    default: true

  crazyauctions.listed:
    default: true

  crazyauctions.view:
    default: true

  crazyauctions.help:
    default: op

  crazyauctions.reload:
    default: op

  crazyauctions.bypass:
    default: op

  crazyauctions.player.*:
    default: false
    children:
      crazyauctions.bid: true
      crazyauctions.sell: true
      crazyauctions.access: true
      crazyauctions.view: true

  crazyauctions.admin:
    default: false
    children:
      crazyauctions.reload: true
      crazyauctions.bypass: true
      crazyauctions.cancel: true