name: '${name}'
main: '${group}.${name}'

authors: ${authors}

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'
folia-supported: true

softdepend: [Vault]

commands:
  crazyauctions:
    description: Opens the Crazy Auctions GUI.
    aliases: [crazyauction, ah, ca]

permissions:
  crazyauctions.access:
    default: true

  crazyauctions.test:
    default: op

  crazyauctions.view:
    default: true

  crazyauctions.reload:
    default: op

  crazyauctions.force-end-all:
    default: op

  crazyauctions.bypass:
    default: false

  crazyauctions.sell:
    default: true

  crazyauctions.bid:
    default: true

  crazyauctions.player.*:
    default: false
    children:
      crazyauctions.bid: true
      crazyauctions.sell: true
      crazyauctions.access: true
      crazyauctions.view: true

  crazyauctions.admin:
    default: false
    children:
      crazyauctions.test: true
      crazyauctions.reload: true
      crazyauctions.bypass: true
      crazyauctions.force-end-all: true